name: plugin_screeb
description: A flutter plugin to integrate Screeb mobile sdk for Android and/or iOS.
version: 0.0.1
homepage: https://screeb.app

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  plugin:
    platforms:
      android:
        package: app.screeb.plugin_screeb
        pluginClass: PluginScreebPlugin
      ios:
        pluginClass: PluginScreebPlugin
